nodes:
- input.live
# - custom_nodes.draw.rotate:
#   rotation: 0
- model.yolo
# - custom_nodes.dabble.tracker_node:
#   maxDisappeared: 60
# - custom_nodes.dabble.counter_node:
#   endpoint: "https://spai-human-counter-backend-api.herokuapp.com/history/"
- dabble.fps
- draw.bbox
# - custom_nodes.customLegend:
#   include: ["fps", "footfall"]
#   position: "top"
- draw.blur_bbox
# - custom_nodes.draw.line
# - custom_nodes.draw.drawCentroid
- output.screen