nodes:
- input.live:
    input_source: 0 # Use Webcam
    input_source: "http://192.168.10.145:8080/stream.mjpeg" # Use http stream
    threading: True
# - custom_nodes.input.customInput: # Use ESP-32 Cam
#       url: "http://192.168.xx.xx/"
- custom_nodes.draw.rotate:
    rotation: 0
- model.yolo
- custom_nodes.dabble.tracker:
    maxDisappeared: 60
- custom_nodes.dabble.counter:
    endpoint: "https://spai-human-counter-backend-api.herokuapp.com/history/"
- dabble.fps
- draw.bbox
- custom_nodes.draw.customLegend:
    include: ["fps", "footfall"]
    position: "top"
- draw.blur_bbox
- custom_nodes.draw.line:
    roi : 0.5
    axis_y : True
- custom_nodes.draw.drawCentroid
- output.screen
- output.media_writer:
    output_dir: 'C:\Users\amir_\OneDrive - Singapore Polytechnic\VSC\PROGRAMMING\PYTHON\Python\SPAI_HumanCounter\human_counter\media'